---
- name: Mac Setup
  hosts: 127.0.0.1
  connection: local
  become: no
  vars:
    brew_packages:
      - git
      - direnv
      - docker-compose
      - jq
      - openssl
      - tree
      - wget
      - java
      - tfenv

    brew_cask_apps:
      # browser系
      - firefox
      - chromium
      # JetBrains系
      - goland
      - webstorm
      # work系
      - slack
      # others
      - docker
      - dropbox
      - meld
      - skitch
      - keepassxc

  tasks:
    - name: Update Homebrew
      homebrew:
        update_homebrew: yes

    - name: Install Homebrew Cask Packages
      homebrew_cask:
        name: "{{ item }}"
        state: "present"
      with_items: "{{ brew_cask_apps }}"

    - name: Install Homebrew Packages
      homebrew:
        name: "{{ brew_packages }}"
        state: "present"
